### ISSUE TITLE
Run individual snapshot tests against each dataset output in `40_Results``

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/pactaCore#55]
I think it is important that, before refactoring, we expand this snapshot test into individual snapshot tests that against each dataset individually. 

I understand that testing the entire dataset will be very slow, so maybe an alternative is to test against a random sample of rows of the dataset?

And then we can have a slowly more complete test that all the datasets are actually identical either in CI or some other check that isn't run very often.

_Originally posted by @jdhoffa in https://github.com/2DegreesInvesting/pactaCore/pull/49#r701106915_

**Comment by maurolepore** [comment]
> I understand that testing the entire dataset will be very slow, so maybe an alternative is to test against a random sample of rows of the dataset?

I don't think `expect_snapshot(list(a, b, c))` is slower than `expect_snapshot(a); expect_snapshot(b); expect_snaphsot(c)`. At least my intent in snapshotting the list was not to save computation time but to avoid duplication. But my approach is likely an off-label use of snapshots -- so I'm very happy to implement what you are asking for.

**Comment by maurolepore** [comment]
> test that all the datasets are actually identical either in CI or some other check that isn't run very often.

Locally, you can skip slow tests with the environment variable  `PACTA_SKIP_SLOW_TESTS=TRUE`. For this I use a local .Renviron (see `usethis::edit_r_environ("project")`).

https://github.com/2DegreesInvesting/pactaCore/blob/037178a85413900b5d0952241bbd3c209ea18511/R/utils.R#L89

**Comment by maurolepore** [comment]
>   I understand that testing the entire dataset will be very slo﻿w ...

Yeah, testing the snapshot of each dataset in full seems to be slow,
apparently because printing and comparing large datasets takes a while.
But the test was already slow because running pacta takes a long while
too. As the workflow is not snappy anyway, for now I prefer to wait a
bit more and have the most comprehensive regression test we can. This
will be less important when we have tests of other kind, and then
we may test just a piece of each dataset.

For reference, right now, using full snapshots test-run_pacta.R takes
aprox 190 seconds in my computer.
